# Generated by Django 4.2.16 on 2025-12-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterservice',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_services', to='staff.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_by_masters', to='staff.service', verbose_name='Услуга'),
        ),
    ]
