# Generated by Django 4.2.16 on 2025-12-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_services', to='staff.service', verbose_name='Услуга'),
        ),
    ]
